# Load Data

In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# Any results you write to the current directory are saved as output.

/kaggle/input/msbd5001-fall2019/train.csv
/kaggle/input/msbd5001-fall2019/samplesubmission.csv
/kaggle/input/msbd5001-fall2019/test.csv
/kaggle/input/test-submission/submission.csv

In [2]:
train = pd.read_csv("/kaggle/input/msbd5001-fall2019/train.csv")
test = pd.read_csv("/kaggle/input/msbd5001-fall2019/test.csv")

In [3]:
testid = pd.read_csv("/kaggle/input/msbd5001-fall2019/test.csv")

In [4]:
test

,id,is_free,price,genres,categories,tags,purchase_date,release_date,total_positive_reviews,total_negative_reviews
0,0,False,3500,"Action,Adventure","Single-player,Full controller support","Action,Adventure,Horror,Third Person,Singlepla...","Oct 28, 2018",22-May-12,2607.0,1122.0
1,1,False,11600,"Action,Adventure,Strategy","Single-player,Multi-player,Online Multi-Player...","Mechs,Strategy,Turn-Based,Turn-Based Tactics,S...","Jul 20, 2019",24-Apr-18,5762.0,2235.0
2,2,False,2100,"Indie,Simulation,Strategy","Single-player,Steam Achievements,Steam Trading...","Strategy,Simulation,Indie,Political,Cold War,P...","Jul 16, 2019",20-Mar-17,687.0,133.0
3,3,False,3600,"Action,Strategy","Single-player,Multi-player,Co-op","Strategy,Action,Military,Tactical","Jan 30, 2018",17-Jul-07,67.0,39.0
4,4,False,3400,"Action,Adventure","Single-player,Co-op,Steam Achievements,Full co...","Open World,Action,Comedy,Co-op,Third-Person Sh...","Feb 24, 2017",22-Aug-13,40344.0,3708.0
...,...,...,...,...,...,...,...,...,...,...
85,85,False,5000,Action,"Single-player,Steam Achievements,Full controll...","Western,FPS,Action,Story Rich,Bullet Time,Shoo...","Mar 23, 2018",22-May-13,9334.0,516.0
86,86,False,3600,"Action,Adventure",Single-player,"Adventure,Action,Ninja,Stealth,Cute,Singleplay...","Mar 3, 2018",14-Sep-09,1245.0,176.0
87,87,False,11200,"Simulation,Strategy","Single-player,Multi-player,Cross-Platform Mult...","Grand Strategy,Strategy,Historical,Simulation,...","Feb 18, 2018",13-Aug-13,33128.0,6350.0
88,88,True,0,"Action,Adventure,RPG,Simulation,Sports,Strategy","Single-player,Multi-player,Co-op,Online Co-op,...","VR,RPG,Action,Sports,Simulation,Adventure,Stra...","Nov 19, 2017",19-Jun-17,5.0,0.0
89,89,False,26800,"Action,Strategy","Single-player,Multi-player,Steam Achievements,...","Strategy,Fantasy,Turn-Based Strategy,RTS,Grand...","Nov 25, 2018",28-Sep-17,17777.0,2594.0

In [5]:
test['tags']

0     Action,Adventure,Horror,Third Person,Singlepla...
1     Mechs,Strategy,Turn-Based,Turn-Based Tactics,S...
2     Strategy,Simulation,Indie,Political,Cold War,P...
3                     Strategy,Action,Military,Tactical
4     Open World,Action,Comedy,Co-op,Third-Person Sh...
                            ...
85    Western,FPS,Action,Story Rich,Bullet Time,Shoo...
86    Adventure,Action,Ninja,Stealth,Cute,Singleplay...
87    Grand Strategy,Strategy,Historical,Simulation,...
88    VR,RPG,Action,Sports,Simulation,Adventure,Stra...
89    Strategy,Fantasy,Turn-Based Strategy,RTS,Grand...
Name: tags, Length: 90, dtype: object

# Process Null Value

In [6]:
test['total_positive_reviews'] = test['total_positive_reviews'].fillna(test['total_positive_reviews'].mean())

In [7]:
test['total_negative_reviews'] = test['total_negative_reviews'].fillna(test['total_negative_reviews'].mean())

In [8]:
test['purchase_date'] = test['purchase_date'].fillna("Jun,2019")

In [9]:
test['release_date'] = test['release_date'].fillna("Jun,2019")

In [10]:
train = train.dropna(axis=0)
combine = [train,test]
train

,id,playtime_forever,is_free,price,genres,categories,tags,purchase_date,release_date,total_positive_reviews,total_negative_reviews
0,0,0.000000,False,3700.0,"Adventure,Casual,Indie","Single-player,Steam Trading Cards,Steam Cloud","Indie,Adventure,Story Rich,Casual,Atmospheric,...","Jul 2, 2018","10 Dec, 2013",372.0,96.0
1,1,0.016667,True,0.0,RPG,"Single-player,Partial Controller Support","Mod,Utilities,RPG,Game Development,Singleplaye...","Nov 26, 2016","12 Aug, 2015",23.0,0.0
2,2,0.000000,False,5000.0,"Adventure,Casual,Indie","Single-player,Full controller support,Steam Tr...","Point & Click,Adventure,Story Rich,Comedy,Indi...","Jul 2, 2018","28 Jan, 2014",3018.0,663.0
3,3,1.533333,False,9900.0,"Action,RPG","Single-player,Multi-player,Steam Achievements,...","Medieval,RPG,Open World,Strategy,Sandbox,Actio...","Nov 28, 2016","31 Mar, 2010",63078.0,1746.0
4,4,22.333333,False,4800.0,"Action,Indie,Strategy","Single-player,Co-op,Steam Achievements,Full co...","Tower Defense,Co-op,Action,Strategy,Online Co-...","Mar 4, 2018","30 Jul, 2012",8841.0,523.0
...,...,...,...,...,...,...,...,...,...,...,...
352,352,0.783333,False,8800.0,"Action,Simulation","Single-player,Multi-player,Online Multi-Player...","Simulation,Action,VR,Flight","Nov 24, 2017","20 Dec, 2016",150.0,91.0
353,353,0.000000,False,6800.0,"Action,Adventure","Single-player,Steam Achievements,Full controll...","Batman,Action,Open World,Superhero,Stealth,Adv...","Aug 15, 2018","23 Jun, 2015",19008.0,4849.0
354,354,0.000000,False,8300.0,"Action,Adventure,RPG","Single-player,Steam Achievements,Full controll...","Action,Hack and Slash,Adventure,RPG,Open World...","Jan 30, 2018","5 Nov, 2015",5099.0,1719.0
355,355,0.000000,False,6800.0,"Action,Adventure","Single-player,Steam Achievements,Full controll...","Action,FPS,Adventure,Shooter,Cyberpunk,Robots,...","Sep 23, 2017","3 Jun, 2016",718.0,159.0
356,356,0.000000,False,10000.0,"Indie,Strategy","Single-player,Multi-player,Co-op,Shared/Split ...","Strategy,Turn-Based Strategy,Indie,Grand Strat...","Mar 5, 2018","5 Dec, 2013",915.0,102.0

In [11]:
train.describe()

,id,playtime_forever,price,total_positive_reviews,total_negative_reviews
count,355.000000,355.000000,3.550000e+02,355.000000,355.000000
mean,178.774648,3.128545,7.154788e+04,15356.115493,3348.991549
std,102.937532,11.243515,9.254761e+05,44032.358308,24706.625113
min,0.000000,0.000000,0.000000e+00,0.000000,0.000000
25%,90.500000,0.000000,3.600000e+03,799.000000,115.500000
50%,179.000000,0.083333,6.800000e+03,2809.000000,437.000000
75%,267.500000,1.575000,9.000000e+03,9666.500000,1220.500000
max,356.000000,113.800000,1.599990e+07,440902.000000,436046.000000

# Label Encoding

In [12]:
def feature_mapping(dfs, feature_name, mapping):
    for df in dfs:
        df[feature_name] = df[feature_name].map(mapping)

In [13]:
is_free_mapping = {False:'1', True:'0'}
feature_mapping([train, test], "is_free", is_free_mapping)
train

,id,playtime_forever,is_free,price,genres,categories,tags,purchase_date,release_date,total_positive_reviews,total_negative_reviews
0,0,0.000000,1,3700.0,"Adventure,Casual,Indie","Single-player,Steam Trading Cards,Steam Cloud","Indie,Adventure,Story Rich,Casual,Atmospheric,...","Jul 2, 2018","10 Dec, 2013",372.0,96.0
1,1,0.016667,0,0.0,RPG,"Single-player,Partial Controller Support","Mod,Utilities,RPG,Game Development,Singleplaye...","Nov 26, 2016","12 Aug, 2015",23.0,0.0
2,2,0.000000,1,5000.0,"Adventure,Casual,Indie","Single-player,Full controller support,Steam Tr...","Point & Click,Adventure,Story Rich,Comedy,Indi...","Jul 2, 2018","28 Jan, 2014",3018.0,663.0
3,3,1.533333,1,9900.0,"Action,RPG","Single-player,Multi-player,Steam Achievements,...","Medieval,RPG,Open World,Strategy,Sandbox,Actio...","Nov 28, 2016","31 Mar, 2010",63078.0,1746.0
4,4,22.333333,1,4800.0,"Action,Indie,Strategy","Single-player,Co-op,Steam Achievements,Full co...","Tower Defense,Co-op,Action,Strategy,Online Co-...","Mar 4, 2018","30 Jul, 2012",8841.0,523.0
...,...,...,...,...,...,...,...,...,...,...,...
352,352,0.783333,1,8800.0,"Action,Simulation","Single-player,Multi-player,Online Multi-Player...","Simulation,Action,VR,Flight","Nov 24, 2017","20 Dec, 2016",150.0,91.0
353,353,0.000000,1,6800.0,"Action,Adventure","Single-player,Steam Achievements,Full controll...","Batman,Action,Open World,Superhero,Stealth,Adv...","Aug 15, 2018","23 Jun, 2015",19008.0,4849.0
354,354,0.000000,1,8300.0,"Action,Adventure,RPG","Single-player,Steam Achievements,Full controll...","Action,Hack and Slash,Adventure,RPG,Open World...","Jan 30, 2018","5 Nov, 2015",5099.0,1719.0
355,355,0.000000,1,6800.0,"Action,Adventure","Single-player,Steam Achievements,Full controll...","Action,FPS,Adventure,Shooter,Cyberpunk,Robots,...","Sep 23, 2017","3 Jun, 2016",718.0,159.0
356,356,0.000000,1,10000.0,"Indie,Strategy","Single-player,Multi-player,Co-op,Shared/Split ...","Strategy,Turn-Based Strategy,Indie,Grand Strat...","Mar 5, 2018","5 Dec, 2013",915.0,102.0

In [14]:
y_train= train['playtime_forever']
X_train = train.drop(columns=['playtime_forever'])
y_train

0       0.000000
1       0.016667
2       0.000000
3       1.533333
4      22.333333
         ...
352     0.783333
353     0.000000
354     0.000000
355     0.000000
356     0.000000
Name: playtime_forever, Length: 355, dtype: float64

In [15]:
y_train.describe()

count    355.000000
mean       3.128545
std       11.243515
min        0.000000
25%        0.000000
50%        0.083333
75%        1.575000
max      113.800000
Name: playtime_forever, dtype: float64

# Process the Date
Process purchase_date and release_date

In [16]:
df = X_train["purchase_date"].str.split(',',expand=True)
X_train["purchase_date"]=df[1]

In [17]:
df = X_train["release_date"].str.split(',',expand=True)
X_train["release_date"]=df[1]

In [18]:
X_train["date_gap"]= X_train.apply(lambda x:int(x["purchase_date"])- int(x["release_date"]),axis=1)

In [19]:
df = test["purchase_date"].str.split(',',expand=True)
test["purchase_date"]=df[1]

In [20]:
df = test["release_date"].str.split('-',expand=True)
test["release_date"]=df[2]

In [21]:
test["date_gap"]= test.apply(lambda x:int(x["purchase_date"])- int(x["release_date"])-2000,axis=1)

In [22]:
test["date_gap"]

0      6
1      1
2      2
3     11
4      4
      ..
85     5
86     9
87     5
88     0
89     1
Name: date_gap, Length: 90, dtype: int64

In [23]:
test.drop(columns=['purchase_date'], inplace=True)
X_train.drop(columns=['purchase_date'], inplace=True)
test.drop(columns=['release_date'], inplace=True)
X_train.drop(columns=['release_date'], inplace=True)

In [24]:
test

,id,is_free,price,genres,categories,tags,total_positive_reviews,total_negative_reviews,date_gap
0,0,1,3500,"Action,Adventure","Single-player,Full controller support","Action,Adventure,Horror,Third Person,Singlepla...",2607.0,1122.0,6
1,1,1,11600,"Action,Adventure,Strategy","Single-player,Multi-player,Online Multi-Player...","Mechs,Strategy,Turn-Based,Turn-Based Tactics,S...",5762.0,2235.0,1
2,2,1,2100,"Indie,Simulation,Strategy","Single-player,Steam Achievements,Steam Trading...","Strategy,Simulation,Indie,Political,Cold War,P...",687.0,133.0,2
3,3,1,3600,"Action,Strategy","Single-player,Multi-player,Co-op","Strategy,Action,Military,Tactical",67.0,39.0,11
4,4,1,3400,"Action,Adventure","Single-player,Co-op,Steam Achievements,Full co...","Open World,Action,Comedy,Co-op,Third-Person Sh...",40344.0,3708.0,4
...,...,...,...,...,...,...,...,...,...
85,85,1,5000,Action,"Single-player,Steam Achievements,Full controll...","Western,FPS,Action,Story Rich,Bullet Time,Shoo...",9334.0,516.0,5
86,86,1,3600,"Action,Adventure",Single-player,"Adventure,Action,Ninja,Stealth,Cute,Singleplay...",1245.0,176.0,9
87,87,1,11200,"Simulation,Strategy","Single-player,Multi-player,Cross-Platform Mult...","Grand Strategy,Strategy,Historical,Simulation,...",33128.0,6350.0,5
88,88,0,0,"Action,Adventure,RPG,Simulation,Sports,Strategy","Single-player,Multi-player,Co-op,Online Co-op,...","VR,RPG,Action,Sports,Simulation,Adventure,Stra...",5.0,0.0,0
89,89,1,26800,"Action,Strategy","Single-player,Multi-player,Steam Achievements,...","Strategy,Fantasy,Turn-Based Strategy,RTS,Grand...",17777.0,2594.0,1

# One Hot Encoding

for 'tags','genres','categories'

In [25]:
tags_dummy = X_train['tags'].str.get_dummies(",").add_prefix("tags_")
for col in tags_dummy.columns:
    if tags_dummy[col].value_counts()[1]<180:
        tags_dummy.drop(col, axis=1, inplace=True)

In [26]:
X_train = X_train.drop(columns='tags')
X_train = pd.concat([X_train, tags_dummy], axis=1)

In [27]:
tags_dummy

,tags_Action,tags_Adventure,tags_Atmospheric,tags_Indie,tags_Singleplayer
0,0,1,1,1,1
1,0,0,0,0,1
2,0,1,0,1,1
3,1,1,0,1,1
4,1,1,0,1,1
...,...,...,...,...,...
352,1,0,0,0,0
353,1,1,1,0,1
354,1,1,0,0,1
355,1,1,0,0,1
356,0,0,0,1,1

In [28]:
test_tags_dummy = test['tags'].str.get_dummies(",").add_prefix("tags_")
test = test.drop(columns='tags')
test = pd.concat([test, test_tags_dummy], axis=1)

In [29]:
generes_dummy = X_train['genres'].str.get_dummies(",").add_prefix("genres_")
'''for col in generes_dummy.columns:
    if  generes_dummy[col].value_counts()[1]<100:
        generes_dummy.drop(col, axis=1, inplace=True)'''

'for col in generes_dummy.columns:\n    if  generes_dummy[col].value_counts()[1]<100:\n        generes_dummy.drop(col, axis=1, inplace=True)'

In [30]:
test_generes_dummy = test['genres'].str.get_dummies(",").add_prefix("genres_")
test = test.drop(columns='genres')
test = pd.concat([test, test_generes_dummy], axis=1)

In [31]:
X_train = X_train.drop(columns='genres')
X_train = pd.concat([X_train, generes_dummy], axis=1)

In [32]:
generes_dummy

,genres_Action,genres_Adventure,genres_Animation & Modeling,genres_Audio Production,genres_Casual,genres_Design & Illustration,genres_Early Access,genres_Free to Play,genres_Gore,genres_Indie,genres_Massively Multiplayer,genres_Nudity,genres_RPG,genres_Racing,genres_Sexual Content,genres_Simulation,genres_Sports,genres_Strategy,genres_Utilities,genres_Violent
0,0,1,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
2,0,1,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
3,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
4,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
352,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
353,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
354,1,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
355,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
356,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0

In [33]:
categories_dummy = X_train['categories'].str.get_dummies(",").add_prefix("categories_")
for col in categories_dummy.columns:
    if  categories_dummy[col].value_counts()[1]<180:
        categories_dummy.drop(col, axis=1, inplace=True)

In [34]:
X_train = X_train.drop(columns='categories')
X_train = pd.concat([X_train, categories_dummy], axis=1)

In [35]:
categories_dummy

,categories_Single-player,categories_Steam Achievements,categories_Steam Cloud,categories_Steam Trading Cards
0,1,0,1,1
1,1,0,0,0
2,1,0,1,1
3,1,1,0,1
4,1,1,1,1
...,...,...,...,...
352,1,1,1,1
353,1,1,1,1
354,1,1,1,1
355,1,1,0,1
356,1,0,0,0

In [36]:
test_categories_dummy = test['categories'].str.get_dummies(",").add_prefix("categories_")
test = test.drop(columns='categories')
test = pd.concat([test,test_categories_dummy], axis=1)

In [37]:
processed_columns = list(X_train.columns[:])

In [38]:
choice_dummies = [col for col in X_train 
               if "_" in col ]

In [39]:
test_dummies = [col for col in test 
               if "_" in col ]

In [40]:
for col in choice_dummies:
    #print("Adding missing feature {}".format(col))
    if col not in test.columns:
        test[col] = 0

In [41]:
test.describe()

,id,price,total_positive_reviews,total_negative_reviews,date_gap,tags_1980s,tags_1990's,tags_2.5D,tags_2D,tags_3D Platformer,...,categories_Steam Trading Cards,categories_Steam Workshop,categories_SteamVR Collectibles,categories_VR Support,genres_Animation & Modeling,genres_Audio Production,genres_Design & Illustration,genres_Racing,genres_Sexual Content,genres_Utilities
count,90.000000,90.000000,90.000000,90.000000,90.000000,90.000000,90.000000,90.000000,90.000000,90.000000,...,90.000000,90.000000,90.000000,90.000000,90.0,90.0,90.0,90.0,90.0,90.0
mean,44.500000,6213.311111,11146.727273,1656.602273,2.677778,0.033333,0.011111,0.011111,0.244444,0.033333,...,0.611111,0.133333,0.044444,0.022222,0.0,0.0,0.0,0.0,0.0,0.0
std,26.124701,4860.918274,23965.791872,5656.019825,2.529945,0.180511,0.105409,0.105409,0.432165,0.180511,...,0.490229,0.341839,0.207235,0.148231,0.0,0.0,0.0,0.0,0.0,0.0
min,0.000000,0.000000,0.000000,0.000000,-1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
25%,22.250000,3600.000000,591.750000,86.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
50%,44.500000,6150.000000,1918.000000,293.500000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,1.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
75%,66.750000,7725.000000,9344.500000,1104.000000,4.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,1.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
max,89.000000,26800.000000,149032.000000,51387.000000,11.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,0.0,0.0,0.0,0.0,0.0,0.0

In [42]:
for col in test.columns:
    if ("_" in col)  and col not in choice_dummies:
#         print("Removing additional feature {}".format(col))
        test.drop(col, axis=1, inplace=True)

In [43]:
test.describe()

,id,price,total_positive_reviews,total_negative_reviews,date_gap,tags_Action,tags_Adventure,tags_Atmospheric,tags_Indie,tags_Singleplayer,...,categories_Single-player,categories_Steam Achievements,categories_Steam Cloud,categories_Steam Trading Cards,genres_Animation & Modeling,genres_Audio Production,genres_Design & Illustration,genres_Racing,genres_Sexual Content,genres_Utilities
count,90.000000,90.000000,90.000000,90.000000,90.000000,90.000000,90.000000,90.000000,90.000000,90.000000,...,90.0,90.000000,90.000000,90.000000,90.0,90.0,90.0,90.0,90.0,90.0
mean,44.500000,6213.311111,11146.727273,1656.602273,2.677778,0.677778,0.822222,0.577778,0.600000,0.855556,...,1.0,0.800000,0.655556,0.611111,0.0,0.0,0.0,0.0,0.0,0.0
std,26.124701,4860.918274,23965.791872,5656.019825,2.529945,0.469946,0.384467,0.496681,0.492642,0.353509,...,0.0,0.402241,0.477849,0.490229,0.0,0.0,0.0,0.0,0.0,0.0
min,0.000000,0.000000,0.000000,0.000000,-1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,1.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
25%,22.250000,3600.000000,591.750000,86.000000,1.000000,0.000000,1.000000,0.000000,0.000000,1.000000,...,1.0,1.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
50%,44.500000,6150.000000,1918.000000,293.500000,2.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.0,1.000000,1.000000,1.000000,0.0,0.0,0.0,0.0,0.0,0.0
75%,66.750000,7725.000000,9344.500000,1104.000000,4.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.0,1.000000,1.000000,1.000000,0.0,0.0,0.0,0.0,0.0,0.0
max,89.000000,26800.000000,149032.000000,51387.000000,11.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.0,1.000000,1.000000,1.000000,0.0,0.0,0.0,0.0,0.0,0.0

In [45]:
Y = train['playtime_forever']
X_train

,id,is_free,price,total_positive_reviews,total_negative_reviews,date_gap,tags_Action,tags_Adventure,tags_Atmospheric,tags_Indie,...,genres_Sexual Content,genres_Simulation,genres_Sports,genres_Strategy,genres_Utilities,genres_Violent,categories_Single-player,categories_Steam Achievements,categories_Steam Cloud,categories_Steam Trading Cards
0,0,1,3700.0,372.0,96.0,5,0,1,1,1,...,0,0,0,0,0,0,1,0,1,1
1,1,0,0.0,23.0,0.0,1,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
2,2,1,5000.0,3018.0,663.0,4,0,1,0,1,...,0,0,0,0,0,0,1,0,1,1
3,3,1,9900.0,63078.0,1746.0,6,1,1,0,1,...,0,0,0,0,0,0,1,1,0,1
4,4,1,4800.0,8841.0,523.0,6,1,1,0,1,...,0,0,0,1,0,0,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
352,352,1,8800.0,150.0,91.0,1,1,0,0,0,...,0,1,0,0,0,0,1,1,1,1
353,353,1,6800.0,19008.0,4849.0,3,1,1,1,0,...,0,0,0,0,0,0,1,1,1,1
354,354,1,8300.0,5099.0,1719.0,3,1,1,0,0,...,0,0,0,0,0,0,1,1,1,1
355,355,1,6800.0,718.0,159.0,1,1,1,0,0,...,0,0,0,0,0,0,1,1,0,1
356,356,1,10000.0,915.0,102.0,5,0,0,0,1,...,0,0,0,1,0,0,1,0,0,0

In [46]:
from mpl_toolkits.mplot3d import Axes3D
from sklearn import datasets
from sklearn.decomposition import PCA
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
import seaborn as sns
import matplotlib.pyplot as plt
from pandas.core.frame import DataFrame

In [49]:
test

,id,is_free,price,total_positive_reviews,total_negative_reviews,date_gap,tags_Action,tags_Adventure,tags_Atmospheric,tags_Indie,...,categories_Single-player,categories_Steam Achievements,categories_Steam Cloud,categories_Steam Trading Cards,genres_Animation & Modeling,genres_Audio Production,genres_Design & Illustration,genres_Racing,genres_Sexual Content,genres_Utilities
0,0,1,3500,2607.0,1122.0,6,1,1,1,0,...,1,0,0,0,0,0,0,0,0,0
1,1,1,11600,5762.0,2235.0,1,1,1,0,0,...,1,1,1,1,0,0,0,0,0,0
2,2,1,2100,687.0,133.0,2,0,0,0,1,...,1,1,0,1,0,0,0,0,0,0
3,3,1,3600,67.0,39.0,11,1,0,0,0,...,1,0,0,0,0,0,0,0,0,0
4,4,1,3400,40344.0,3708.0,4,1,1,0,0,...,1,1,1,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85,85,1,5000,9334.0,516.0,5,1,1,1,0,...,1,1,1,1,0,0,0,0,0,0
86,86,1,3600,1245.0,176.0,9,1,1,0,1,...,1,0,0,0,0,0,0,0,0,0
87,87,1,11200,33128.0,6350.0,5,0,0,0,0,...,1,1,1,1,0,0,0,0,0,0
88,88,0,0,5.0,0.0,0,1,1,0,0,...,1,1,1,0,0,0,0,0,0,0
89,89,1,26800,17777.0,2594.0,1,1,0,1,0,...,1,1,0,1,0,0,0,0,0,0

In [50]:
X_train

,id,is_free,price,total_positive_reviews,total_negative_reviews,date_gap,tags_Action,tags_Adventure,tags_Atmospheric,tags_Indie,...,genres_Sexual Content,genres_Simulation,genres_Sports,genres_Strategy,genres_Utilities,genres_Violent,categories_Single-player,categories_Steam Achievements,categories_Steam Cloud,categories_Steam Trading Cards
0,0,1,3700.0,372.0,96.0,5,0,1,1,1,...,0,0,0,0,0,0,1,0,1,1
1,1,0,0.0,23.0,0.0,1,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
2,2,1,5000.0,3018.0,663.0,4,0,1,0,1,...,0,0,0,0,0,0,1,0,1,1
3,3,1,9900.0,63078.0,1746.0,6,1,1,0,1,...,0,0,0,0,0,0,1,1,0,1
4,4,1,4800.0,8841.0,523.0,6,1,1,0,1,...,0,0,0,1,0,0,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
352,352,1,8800.0,150.0,91.0,1,1,0,0,0,...,0,1,0,0,0,0,1,1,1,1
353,353,1,6800.0,19008.0,4849.0,3,1,1,1,0,...,0,0,0,0,0,0,1,1,1,1
354,354,1,8300.0,5099.0,1719.0,3,1,1,0,0,...,0,0,0,0,0,0,1,1,1,1
355,355,1,6800.0,718.0,159.0,1,1,1,0,0,...,0,0,0,0,0,0,1,1,0,1
356,356,1,10000.0,915.0,102.0,5,0,0,0,1,...,0,0,0,1,0,0,1,0,0,0

In [51]:
from sklearn.model_selection import train_test_split
# 拆分测试集和验证集
X_train, X_val, y_train, y_val = train_test_split(X_train,Y,test_size=0.2)
print("X_train:",X_train.shape)
print("y_train:",y_train.shape)
print("X_val:",X_val.shape)
print("y_val:",y_val.shape)
print("test:",test.shape)

X_train: (284, 35)
y_train: (284,)
X_val: (71, 35)
y_val: (71,)
test: (90, 35)

In [52]:
test.describe()

,id,price,total_positive_reviews,total_negative_reviews,date_gap,tags_Action,tags_Adventure,tags_Atmospheric,tags_Indie,tags_Singleplayer,...,categories_Single-player,categories_Steam Achievements,categories_Steam Cloud,categories_Steam Trading Cards,genres_Animation & Modeling,genres_Audio Production,genres_Design & Illustration,genres_Racing,genres_Sexual Content,genres_Utilities
count,90.000000,90.000000,90.000000,90.000000,90.000000,90.000000,90.000000,90.000000,90.000000,90.000000,...,90.0,90.000000,90.000000,90.000000,90.0,90.0,90.0,90.0,90.0,90.0
mean,44.500000,6213.311111,11146.727273,1656.602273,2.677778,0.677778,0.822222,0.577778,0.600000,0.855556,...,1.0,0.800000,0.655556,0.611111,0.0,0.0,0.0,0.0,0.0,0.0
std,26.124701,4860.918274,23965.791872,5656.019825,2.529945,0.469946,0.384467,0.496681,0.492642,0.353509,...,0.0,0.402241,0.477849,0.490229,0.0,0.0,0.0,0.0,0.0,0.0
min,0.000000,0.000000,0.000000,0.000000,-1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,1.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
25%,22.250000,3600.000000,591.750000,86.000000,1.000000,0.000000,1.000000,0.000000,0.000000,1.000000,...,1.0,1.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
50%,44.500000,6150.000000,1918.000000,293.500000,2.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.0,1.000000,1.000000,1.000000,0.0,0.0,0.0,0.0,0.0,0.0
75%,66.750000,7725.000000,9344.500000,1104.000000,4.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.0,1.000000,1.000000,1.000000,0.0,0.0,0.0,0.0,0.0,0.0
max,89.000000,26800.000000,149032.000000,51387.000000,11.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.0,1.000000,1.000000,1.000000,0.0,0.0,0.0,0.0,0.0,0.0

In [53]:
from sklearn.datasets import load_boston
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import SGDRegressor
from sklearn import neighbors
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_squared_log_error
from sklearn.metrics import mean_absolute_error

# Normalization

In [54]:
ss_X = StandardScaler()
param = ss_X.fit(X_train['price'].values.reshape(-1,1))
X_train['price'] = ss_X.fit_transform(X_train['price'].values.reshape(-1, 1),param)
param1 = ss_X.fit(X_train['total_positive_reviews'].values.reshape(-1,1))
X_train['total_positive_reviews'] = ss_X.fit_transform(X_train['total_positive_reviews'].values.reshape(-1, 1),param1)
param2 = ss_X.fit(X_train['total_negative_reviews'].values.reshape(-1,1))
X_train['total_negative_reviews'] = ss_X.fit_transform(X_train['total_negative_reviews'].values.reshape(-1, 1),param2)

/opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
/opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys

In [55]:
ss_X = StandardScaler()
param = ss_X.fit(X_val['price'].values.reshape(-1,1))
X_val['price'] = ss_X.fit_transform(X_val['price'].values.reshape(-1, 1),param)
param1 = ss_X.fit(X_val['total_positive_reviews'].values.reshape(-1,1))
X_val['total_positive_reviews'] = ss_X.fit_transform(X_val['total_positive_reviews'].values.reshape(-1, 1),param1)
param2 = ss_X.fit(X_val['total_negative_reviews'].values.reshape(-1,1))
X_val['total_negative_reviews'] = ss_X.fit_transform(X_val['total_negative_reviews'].values.reshape(-1, 1),param2)

/opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
/opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys

In [56]:
ss_X = StandardScaler()
param = ss_X.fit(test['price'].values.reshape(-1,1))
test['price'] = ss_X.fit_transform(test['price'].values.reshape(-1, 1),param)
param1 = ss_X.fit(test['total_positive_reviews'].values.reshape(-1,1))
test['total_positive_reviews'] = ss_X.fit_transform(test['total_positive_reviews'].values.reshape(-1, 1),param1)
param2 = ss_X.fit(test['total_negative_reviews'].values.reshape(-1,1))
test['total_negative_reviews'] = ss_X.fit_transform(test['total_negative_reviews'].values.reshape(-1, 1),param2)

In [57]:
X_train = X_train.drop(columns=['id'])
X_val = X_val.drop(columns=['id'])
test = test.drop(columns = ['id'])

In [58]:
X_train['is_free'] = X_train['is_free'].str.replace(',','').astype(int)
test['is_free'] = test['is_free'].str.replace(',','').astype(int)
X_val['is_free'] = X_val['is_free'].str.replace(',','').astype(int)

# Training Model

In [59]:
import xgboost as xgb
xgb_model = xgb.XGBRegressor(max_depth=7, learning_rate=0.1, n_estimators=50, verbosity=1,gamma=0.1,colsample_bylevel=0.88,
                             tree_method='auto', reg_alpha=0.05, reg_lambda=0.05)
xgb_model.fit(X_train, y_train, eval_metric='rmse', verbose=True,
            eval_set=[(X_val, y_val)], early_stopping_rounds=20)

[10:58:52] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[0]	validation_0-rmse:6.84652
Will train until validation_0-rmse hasn't improved in 20 rounds.
[1]	validation_0-rmse:6.86108
[2]	validation_0-rmse:6.91923
[3]	validation_0-rmse:6.94206
[4]	validation_0-rmse:6.83132

/opt/conda/lib/python3.6/site-packages/xgboost/core.py:587: FutureWarning: Series.base is deprecated and will be removed in a future version
  if getattr(data, 'base', None) is not None and \

[5]	validation_0-rmse:6.96541
[6]	validation_0-rmse:6.93138
[7]	validation_0-rmse:6.94706
[8]	validation_0-rmse:7.04803
[9]	validation_0-rmse:7.13221
[10]	validation_0-rmse:7.13579
[11]	validation_0-rmse:7.22524
[12]	validation_0-rmse:7.26125
[13]	validation_0-rmse:7.35573
[14]	validation_0-rmse:7.40374
[15]	validation_0-rmse:7.44535
[16]	validation_0-rmse:7.48874
[17]	validation_0-rmse:7.53798
[18]	validation_0-rmse:7.5712
[19]	validation_0-rmse:7.57935
[20]	validation_0-rmse:7.59746
[21]	validation_0-rmse:7.60884
[22]	validation_0-rmse:7.6241
[23]	validation_0-rmse:7.66128
[24]	validation_0-rmse:7.70412
Stopping. Best iteration:
[4]	validation_0-rmse:6.83132

XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=0.88,
             colsample_bynode=1, colsample_bytree=1, gamma=0.1,
             importance_type='gain', learning_rate=0.1, max_delta_step=0,
             max_depth=7, min_child_weight=1, missing=None, n_estimators=50,
             n_jobs=1, nthread=None, objective='reg:linear', random_state=0,
             reg_alpha=0.05, reg_lambda=0.05, scale_pos_weight=1, seed=None,
             silent=None, subsample=1, tree_method='auto', verbosity=1)

In [60]:
from sklearn.metrics import mean_squared_error
from math import sqrt
xgb_y_pred = xgb_model.predict(X_val)
rms = sqrt(mean_squared_error(y_val, xgb_y_pred))
print(rms)

6.831317008652337

In [61]:
test1= test.fillna(0)
test1 = test1[['is_free', 'price', 'total_positive_reviews', 'total_negative_reviews', 'date_gap', 'tags_Action', 'tags_Adventure', 'tags_Atmospheric', 'tags_Indie', 'tags_Singleplayer', 'genres_Action', 'genres_Adventure', 'genres_Animation & Modeling', 'genres_Audio Production', 'genres_Casual', 'genres_Design & Illustration', 'genres_Early Access', 'genres_Free to Play', 'genres_Gore', 'genres_Indie', 'genres_Massively Multiplayer', 'genres_Nudity', 'genres_RPG', 'genres_Racing', 'genres_Sexual Content', 'genres_Simulation', 'genres_Sports', 'genres_Strategy', 'genres_Utilities', 'genres_Violent', 'categories_Single-player', 'categories_Steam Achievements', 'categories_Steam Cloud', 'categories_Steam Trading Cards']]

In [62]:
xgb_test_pred = xgb_model.predict(test1)

In [63]:
xgb_test_pred

array([ 0.43677813,  2.5583282 ,  0.41295582,  0.3630251 ,  0.75725883,
        1.2245219 ,  0.3988706 ,  0.6981524 ,  0.4494128 ,  0.74362314,
        1.0504467 ,  0.7107678 ,  0.91197884,  1.195617  ,  6.8649187 ,
        0.41295582,  0.41541445,  0.3988706 ,  1.2245219 ,  1.1112856 ,
        1.0504467 ,  0.5816731 ,  0.35952634,  1.0504467 ,  0.41295582,
        0.41541445,  1.0504467 ,  1.0504467 ,  1.4016881 ,  1.1112856 ,
        1.0504467 , 13.184423  ,  0.3988706 ,  1.0504467 ,  0.4828032 ,
        1.0504467 ,  1.195617  ,  1.2373477 ,  1.0504467 ,  0.6443292 ,
        0.7839958 ,  2.4276075 ,  1.1112856 ,  0.41541445,  1.0504467 ,
        0.5732538 ,  0.42196435,  0.4872817 ,  3.2654002 ,  2.3679957 ,
        0.50799793,  0.68817014,  0.7107678 ,  0.45970944,  0.53860366,
        0.41295582,  1.6007695 ,  0.66017544,  0.50799793,  0.83177996,
        1.1112856 ,  0.45507634,  0.4096262 ,  7.828645  ,  0.4096262 ,
        0.4096262 ,  0.3983984 ,  0.4096262 ,  0.4096262 ,  0.3988706 ,
        0.4096262 , 13.184423  ,  0.71020824,  5.338548  ,  0.41541445,
        1.3306518 ,  7.7699585 ,  1.0134819 ,  0.9094355 ,  0.67320496,
        0.4096262 ,  1.0504467 ,  0.41541445, 19.726778  ,  0.56156874,
        1.195617  ,  0.45507634, 13.184423  ,  2.5009894 ,  7.689706  ],
      dtype=float32)

In [64]:
knn = neighbors.KNeighborsRegressor(n_neighbors=15, weights='uniform', algorithm='auto', leaf_size=30, p=2, metric='minkowski')
knn.fit(X_train, y_train)

KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='minkowski',
                    metric_params=None, n_jobs=None, n_neighbors=15, p=2,
                    weights='uniform')

In [65]:
knn_y_pred = knn.predict(X_val)
rms = sqrt(mean_squared_error(y_val, knn_y_pred))
print(rms)

5.731670397005232

In [66]:
knn_test_pred = knn.predict(test1)

In [67]:
lr = LinearRegression()
lr.fit(X_train, y_train)
lr_y_pred = lr.predict(X_val)
rms = sqrt(mean_squared_error(y_val, lr_y_pred))
print(rms)

9.33766106545302

In [68]:
lr_test_pred = lr.predict(test1)

In [69]:
sgdr = SGDRegressor()
sgdr.fit(X_train, y_train)
sgdr_y_pred = sgdr.predict(X_val)
rms = sqrt(mean_squared_error(y_val, sgdr_y_pred))
print(rms)

8.746699269121688

In [70]:
sgdr_test_pred = sgdr.predict(test1)

In [71]:
from sklearn.ensemble import AdaBoostRegressor
AdaBoost = AdaBoostRegressor()
AdaBoost.fit(X_train, y_train)

AdaBoost_y_pred = AdaBoost.predict(X_val)
rms = sqrt(mean_squared_error(y_val, AdaBoost_y_pred))
print(rms)

8.803610873963175

In [72]:
AdaBoost_test_pred = AdaBoost.predict(test1)

In [73]:
AdaBoost_test_pred

array([ 4.13576389, 12.00555556,  8.07579909,  3.07777778, 17.31987768,
       12.799375  ,  4.10121528,  3.07777778,  6.321875  , 11.0579096 ,
        3.39920635,  2.61519824,  6.15130719,  3.57060606, 12.00555556,
        8.23529412,  3.39920635,  4.10121528, 11.0579096 ,  2.95878553,
        2.61519824,  6.321875  ,  2.95878553,  2.95878553,  8.23529412,
        4.78333333,  2.95878553,  4.10121528,  3.57060606,  3.57060606,
        2.61519824, 23.64884058,  4.10121528,  4.10121528,  2.61519824,
        2.95878553,  3.57060606,  8.07579909,  4.10121528,  3.07777778,
        4.10121528,  4.10121528,  4.78333333,  5.36904762,  4.10121528,
        8.07579909,  2.61519824,  4.56190476, 12.00555556, 11.0579096 ,
        5.36904762,  2.95878553,  2.61519824,  5.36904762,  3.07777778,
        6.15130719,  9.27820513, 11.0579096 ,  7.11333333,  4.56190476,
        2.95878553,  3.07777778,  4.78333333, 20.61666667,  5.36904762,
        4.10121528,  7.11333333,  4.10121528,  5.36904762,  2.95878553,
        5.36904762, 14.33333333,  9.64029536, 16.35497076,  4.78333333,
       14.21481481, 23.62876984,  8.23529412, 11.0579096 ,  3.39920635,
        4.78333333,  4.10121528,  3.39920635, 23.62876984,  6.15130719,
        3.07777778,  3.07777778, 32.76666667, 13.68730159, 12.00555556])

In [74]:
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
GBoost = GradientBoostingRegressor(n_estimators=150, learning_rate=0.05,
                                   max_depth=5, max_features='sqrt',
                                   min_samples_leaf=15, min_samples_split=10, 
                                   loss='huber', random_state =5)
GBoost.fit(X_train, y_train)
GBoost_y_pred = GBoost.predict(X_val)
rms = sqrt(mean_squared_error(y_val, GBoost_y_pred))
print(rms)

6.210600416057679

In [75]:
from keras.models import *
from keras.layers import *

from keras.utils.np_utils import *
from keras import backend
from keras import regularizers

def rmse(y_true, y_pred):
    return backend.sqrt(backend.mean(backend.square(y_pred - y_true), axis=-1))

model = Sequential()
model.add(Dense(200, input_dim=X_train.shape[1], activation="relu",
                kernel_regularizer=regularizers.l2(0.01)))
model.add(Dropout(0.5))
# model.add(Dense(200, activation="relu",
#                 kernel_regularizer=regularizers.l2(0.01)))
# model.add(Dropout(0.5))
model.add(Dense(100, activation="relu",kernel_regularizer=regularizers.l2(0.01)))
model.add(Dropout(0.5))
# model.add(Dense(50, activation="relu",kernel_regularizer=regularizers.l2(0.01)))
# model.add(Dropout(0.5))
model.add(Dense(25, activation="relu",kernel_regularizer=regularizers.l2(0.01)))
model.add(Dropout(0.5))
model.add(Dense(1, activation="linear",kernel_regularizer=regularizers.l2(0.01)))

model.compile(loss=rmse, optimizer='adam', metrics=['mae'])
print("training starts.....")
model.fit(X_train,y_train,epochs=100,batch_size=800)

Using TensorFlow backend.

training starts.....
Epoch 1/100
284/284 [==============================] - 0s 1ms/step - loss: 6.4488 - mae: 4.1399
Epoch 2/100
284/284 [==============================] - 0s 18us/step - loss: 6.1856 - mae: 3.8931
Epoch 3/100
284/284 [==============================] - 0s 16us/step - loss: 6.1465 - mae: 3.8728
Epoch 4/100
284/284 [==============================] - 0s 19us/step - loss: 6.0276 - mae: 3.7737
Epoch 5/100
284/284 [==============================] - 0s 17us/step - loss: 5.9986 - mae: 3.7653
Epoch 6/100
284/284 [==============================] - 0s 17us/step - loss: 5.8928 - mae: 3.6806
Epoch 7/100
284/284 [==============================] - 0s 16us/step - loss: 5.8751 - mae: 3.6845
Epoch 8/100
284/284 [==============================] - 0s 16us/step - loss: 5.7500 - mae: 3.5812
Epoch 9/100
284/284 [==============================] - 0s 16us/step - loss: 5.7740 - mae: 3.6273
Epoch 10/100
284/284 [==============================] - 0s 16us/step - loss: 5.7432 - mae: 3.6189
Epoch 11/100
284/284 [==============================] - 0s 16us/step - loss: 5.6853 - mae: 3.5834
Epoch 12/100
284/284 [==============================] - 0s 16us/step - loss: 5.6484 - mae: 3.5691
Epoch 13/100
284/284 [==============================] - 0s 16us/step - loss: 5.6116 - mae: 3.5549
Epoch 14/100
284/284 [==============================] - 0s 16us/step - loss: 5.5284 - mae: 3.4945
Epoch 15/100
284/284 [==============================] - 0s 18us/step - loss: 5.5929 - mae: 3.5814
Epoch 16/100
284/284 [==============================] - 0s 17us/step - loss: 5.5483 - mae: 3.5595
Epoch 17/100
284/284 [==============================] - 0s 16us/step - loss: 5.4888 - mae: 3.5226
Epoch 18/100
284/284 [==============================] - 0s 17us/step - loss: 5.4505 - mae: 3.5069
Epoch 19/100
284/284 [==============================] - 0s 17us/step - loss: 5.3984 - mae: 3.4772
Epoch 20/100
284/284 [==============================] - 0s 17us/step - loss: 5.4193 - mae: 3.5203
Epoch 21/100
284/284 [==============================] - 0s 16us/step - loss: 5.3634 - mae: 3.4866
Epoch 22/100
284/284 [==============================] - 0s 16us/step - loss: 5.3723 - mae: 3.5175
Epoch 23/100
284/284 [==============================] - 0s 15us/step - loss: 5.3233 - mae: 3.4904
Epoch 24/100
284/284 [==============================] - 0s 18us/step - loss: 5.2743 - mae: 3.4632
Epoch 25/100
284/284 [==============================] - 0s 15us/step - loss: 5.2914 - mae: 3.5019
Epoch 26/100
284/284 [==============================] - 0s 17us/step - loss: 5.2508 - mae: 3.4828
Epoch 27/100
284/284 [==============================] - 0s 16us/step - loss: 5.2089 - mae: 3.4621
Epoch 28/100
284/284 [==============================] - 0s 15us/step - loss: 5.1829 - mae: 3.4573
Epoch 29/100
284/284 [==============================] - 0s 16us/step - loss: 5.1774 - mae: 3.4727
Epoch 30/100
284/284 [==============================] - 0s 14us/step - loss: 5.1583 - mae: 3.4743
Epoch 31/100
284/284 [==============================] - 0s 17us/step - loss: 5.0736 - mae: 3.4102
Epoch 32/100
284/284 [==============================] - 0s 14us/step - loss: 5.1204 - mae: 3.4772
Epoch 33/100
284/284 [==============================] - 0s 17us/step - loss: 5.0526 - mae: 3.4296
Epoch 34/100
284/284 [==============================] - 0s 17us/step - loss: 5.0474 - mae: 3.4442
Epoch 35/100
284/284 [==============================] - 0s 17us/step - loss: 5.0198 - mae: 3.4362
Epoch 36/100
284/284 [==============================] - 0s 17us/step - loss: 5.0133 - mae: 3.4491
Epoch 37/100
284/284 [==============================] - 0s 17us/step - loss: 4.9803 - mae: 3.4353
Epoch 38/100
284/284 [==============================] - 0s 16us/step - loss: 4.9602 - mae: 3.4341
Epoch 39/100
284/284 [==============================] - 0s 16us/step - loss: 4.9390 - mae: 3.4316
Epoch 40/100
284/284 [==============================] - 0s 17us/step - loss: 4.9164 - mae: 3.4275
Epoch 41/100
284/284 [==============================] - 0s 16us/step - loss: 4.8793 - mae: 3.4085
Epoch 42/100
284/284 [==============================] - 0s 19us/step - loss: 4.8705 - mae: 3.4177
Epoch 43/100
284/284 [==============================] - 0s 18us/step - loss: 4.8359 - mae: 3.4008
Epoch 44/100
284/284 [==============================] - 0s 16us/step - loss: 4.8121 - mae: 3.3945
Epoch 45/100
284/284 [==============================] - 0s 16us/step - loss: 4.8180 - mae: 3.4175
Epoch 46/100
284/284 [==============================] - 0s 17us/step - loss: 4.7435 - mae: 3.3600
Epoch 47/100
284/284 [==============================] - 0s 15us/step - loss: 4.7451 - mae: 3.3785
Epoch 48/100
284/284 [==============================] - 0s 16us/step - loss: 4.7466 - mae: 3.3965
Epoch 49/100
284/284 [==============================] - 0s 16us/step - loss: 4.7192 - mae: 3.3855
Epoch 50/100
284/284 [==============================] - 0s 18us/step - loss: 4.6807 - mae: 3.3629
Epoch 51/100
284/284 [==============================] - 0s 19us/step - loss: 4.6839 - mae: 3.3821
Epoch 52/100
284/284 [==============================] - 0s 16us/step - loss: 4.6579 - mae: 3.3719
Epoch 53/100
284/284 [==============================] - 0s 16us/step - loss: 4.6101 - mae: 3.3396
Epoch 54/100
284/284 [==============================] - 0s 17us/step - loss: 4.6484 - mae: 3.3931
Epoch 55/100
284/284 [==============================] - 0s 16us/step - loss: 4.6539 - mae: 3.4136
Epoch 56/100
284/284 [==============================] - 0s 16us/step - loss: 4.6301 - mae: 3.4047
Epoch 57/100
284/284 [==============================] - 0s 16us/step - loss: 4.4922 - mae: 3.2816
Epoch 58/100
284/284 [==============================] - 0s 16us/step - loss: 4.5715 - mae: 3.3754
Epoch 59/100
284/284 [==============================] - 0s 16us/step - loss: 4.4357 - mae: 3.2537
Epoch 60/100
284/284 [==============================] - 0s 16us/step - loss: 4.5128 - mae: 3.3449
Epoch 61/100
284/284 [==============================] - 0s 16us/step - loss: 4.5484 - mae: 3.3942
Epoch 62/100
284/284 [==============================] - 0s 16us/step - loss: 4.4954 - mae: 3.3547
Epoch 63/100
284/284 [==============================] - 0s 17us/step - loss: 4.4236 - mae: 3.2963
Epoch 64/100
284/284 [==============================] - 0s 17us/step - loss: 4.4502 - mae: 3.3361
Epoch 65/100
284/284 [==============================] - 0s 19us/step - loss: 4.3340 - mae: 3.2327
Epoch 66/100
284/284 [==============================] - 0s 16us/step - loss: 4.3903 - mae: 3.3017
Epoch 67/100
284/284 [==============================] - 0s 16us/step - loss: 4.2934 - mae: 3.2172
Epoch 68/100
284/284 [==============================] - 0s 16us/step - loss: 4.3624 - mae: 3.2984
Epoch 69/100
284/284 [==============================] - 0s 16us/step - loss: 4.3328 - mae: 3.2807
Epoch 70/100
284/284 [==============================] - 0s 17us/step - loss: 4.3692 - mae: 3.3288
Epoch 71/100
284/284 [==============================] - 0s 17us/step - loss: 4.2744 - mae: 3.2457
Epoch 72/100
284/284 [==============================] - 0s 18us/step - loss: 4.3388 - mae: 3.3216
Epoch 73/100
284/284 [==============================] - 0s 16us/step - loss: 4.2266 - mae: 3.2206
Epoch 74/100
284/284 [==============================] - 0s 17us/step - loss: 4.2201 - mae: 3.2251
Epoch 75/100
284/284 [==============================] - 0s 15us/step - loss: 4.2396 - mae: 3.2553
Epoch 76/100
284/284 [==============================] - 0s 14us/step - loss: 4.2347 - mae: 3.2610
Epoch 77/100
284/284 [==============================] - 0s 16us/step - loss: 4.1833 - mae: 3.2200
Epoch 78/100
284/284 [==============================] - 0s 15us/step - loss: 4.1800 - mae: 3.2269
Epoch 79/100
284/284 [==============================] - 0s 16us/step - loss: 4.2298 - mae: 3.2867
Epoch 80/100
284/284 [==============================] - 0s 16us/step - loss: 4.2054 - mae: 3.2721
Epoch 81/100
284/284 [==============================] - 0s 17us/step - loss: 4.2891 - mae: 3.3656
Epoch 82/100
284/284 [==============================] - 0s 15us/step - loss: 4.1069 - mae: 3.1931
Epoch 83/100
284/284 [==============================] - 0s 17us/step - loss: 4.0239 - mae: 3.1198
Epoch 84/100
284/284 [==============================] - 0s 16us/step - loss: 3.9807 - mae: 3.0859
Epoch 85/100
284/284 [==============================] - 0s 18us/step - loss: 4.1868 - mae: 3.3010
Epoch 86/100
284/284 [==============================] - 0s 17us/step - loss: 4.0306 - mae: 3.1538
Epoch 87/100
284/284 [==============================] - 0s 17us/step - loss: 4.0543 - mae: 3.1863
Epoch 88/100
284/284 [==============================] - 0s 16us/step - loss: 4.0245 - mae: 3.1649
Epoch 89/100
284/284 [==============================] - 0s 15us/step - loss: 3.9873 - mae: 3.1363
Epoch 90/100
284/284 [==============================] - 0s 17us/step - loss: 3.9887 - mae: 3.1461
Epoch 91/100
284/284 [==============================] - 0s 16us/step - loss: 3.9461 - mae: 3.1116
Epoch 92/100
284/284 [==============================] - 0s 16us/step - loss: 3.9102 - mae: 3.0836
Epoch 93/100
284/284 [==============================] - 0s 17us/step - loss: 4.0892 - mae: 3.2704
Epoch 94/100
284/284 [==============================] - 0s 16us/step - loss: 3.9866 - mae: 3.1756
Epoch 95/100
284/284 [==============================] - 0s 17us/step - loss: 4.0254 - mae: 3.2220
Epoch 96/100
284/284 [==============================] - 0s 15us/step - loss: 3.8887 - mae: 3.0929
Epoch 97/100
284/284 [==============================] - 0s 18us/step - loss: 3.9045 - mae: 3.1160
Epoch 98/100
284/284 [==============================] - 0s 17us/step - loss: 3.9424 - mae: 3.1612
Epoch 99/100
284/284 [==============================] - 0s 16us/step - loss: 4.0462 - mae: 3.2722
Epoch 100/100
284/284 [==============================] - 0s 17us/step - loss: 3.9563 - mae: 3.1895

In [76]:
'''nn_y_train_pred = model.predict(X_train).flatten()
rms = sqrt(mean_squared_error(y_train, nn_y_train_pred))
print(rms)'''

'nn_y_train_pred = model.predict(X_train).flatten()\nrms = sqrt(mean_squared_error(y_train, nn_y_train_pred))\nprint(rms)'

In [77]:
nn_test_pred = model.predict(test1)

In [78]:
#nn_test_pred

In [79]:
#nn_test_pred=nn_test_pred.reshape(1,-1)

In [81]:
sgdr_test_pred

array([ 8.24388928e-01,  3.96519541e+00,  2.10238936e+00, -5.75725905e+00,
        8.98602688e+00,  5.17853605e+00,  1.22919860e+00, -2.27612830e+00,
       -5.17073514e-01,  6.37155342e+00,  1.62999088e+00, -2.66736528e+00,
        4.74295566e+00,  4.63646094e+00,  6.03549153e+00,  1.11463709e+00,
        3.33587380e-01, -7.71583964e-01,  5.51375728e+00,  2.78051010e+00,
        2.03786332e+00,  4.88577633e+00, -2.92232710e-01,  1.00978474e+00,
        1.91804171e-02,  2.51365689e+00,  1.59100502e+00,  2.69719110e+00,
        2.06758852e+00,  3.98662986e+00,  2.96436114e+00,  3.54434861e+01,
        1.05970819e+00,  7.50044841e-01,  2.48764028e+00,  1.59052014e+00,
        3.27864428e+00,  7.98954036e+00,  3.84607118e+00, -1.00650342e-01,
        3.30175779e-01,  4.59696523e+00,  3.03890639e+00,  2.81745568e+00,
        3.02302489e+00,  4.24665233e+00,  1.46111803e+00, -8.64493004e-02,
        2.23282195e+00,  5.92765194e+00, -3.33044338e-01,  4.97328689e+00,
        5.65521508e-01,  1.56648629e+00,  4.46786296e+00,  1.56246919e+00,
        4.77175929e+00,  4.91398459e+00,  4.58026953e+00,  3.55451764e+00,
        6.30632796e+00, -9.54640343e-01, -4.15493095e-02,  1.09953853e+01,
       -7.36199015e-01,  2.37417453e+00,  2.21495503e+00, -1.00683995e+00,
        1.69481968e+00, -4.71140410e-01,  2.41882334e+00,  1.47880830e+01,
        6.12971802e+00,  2.39783942e+01,  3.93788841e+00,  2.50050149e+01,
        2.77800503e+01,  7.89463917e+00,  3.38847975e+00,  4.71786798e-01,
        2.81877210e+00,  2.79874788e+00,  9.18133445e-01,  9.58221352e+00,
        4.88835190e+00,  1.44759803e+00, -2.00270333e+00,  6.85905702e+00,
        2.71385048e+00,  5.26130384e+00])

In [82]:
submission = pd.DataFrame({
        'id': testid['id'],
        "playtime_forever": sgdr_test_pred
    })

In [83]:
submission.describe()

              id  playtime_forever
count  90.000000         90.000000
mean   44.500000          3.921622
std    26.124701          6.130406
min     0.000000         -5.757259
25%    22.250000          0.941046
50%    44.500000          2.705521
75%    66.750000          4.857272
max    89.000000         35.443486

In [84]:
submission[submission < 0] = 0

In [85]:
submission.describe()

              id  playtime_forever
count  90.000000         90.000000
mean   44.500000          4.121787
std    26.124701          5.946075
min     0.000000          0.000000
25%    22.250000          0.941046
50%    44.500000          2.705521
75%    66.750000          4.857272
max    89.000000         35.443486

In [86]:
submission.to_csv('submission.csv',index=False)